
export const tasksConstants = {
    GET_ALL_TASKS_REQUEST: 'GET_ALL_TASKS_REQUEST',
    GET_ALL_TASKS_SUCCESS: 'GET_ALL_TASKS_SUCCESS',
    GET_ALL_TASKS_FAILURE: 'GET_ALL_TASKS_FAILURE',
    ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',
    DELETE_TASK_BY_ID_REQUEST: 'DELETE_TASK_BY_ID_REQUEST',
    DELETE_TASK_BY_ID_SUCCESS: 'DELETE_TASK_BY_ID_SUCCESS',
    DELETE_TASK_BY_ID_FAILURE: 'DELETE_TASK_BY_ID_FAILURE',
    CHANGE_TASK_STATUS_REQUEST:'CHANGE_TASK_STATUS_REQUEST',
    CHANGE_TASK_STATUS_SUCCESS:'CHANGE_TASK_STATUS_SUCCESS',
    CHANGE_TASK_STATUS_FAILURE:'CHANGE_TASK_STATUS_FAILURE'

}

